Rename DOM AST class TypePattern to AbstractTypePattern
Since JDT Core 3.27 (Java 17), there is a name clash, because the new
class org.eclipse.jdt.core.dom.TypePattern (JEP 406) gets relocated to
org.aspectj.org.eclipse.jdt.core.dom.TypePattern during shading.
Fortunately, this made tests like AjASTTest and AjAST5Test fail with
rather nasty errors like:

java.lang.VerifyError: Bad return type (...)
  Type 'org/aspectj/org/eclipse/jdt/core/dom/TypePattern' (...) is not
  assignable to 'org/aspectj/org/eclipse/jdt/core/dom/Pattern' (...)

TODO: Update AJDT references to the renamed class in the following
classes after refreshing the AspectJ sources:
  - ExtraPackageReferenceFinder
  - ExtraTypeReferenceFinder
This also means, that for Eclipse 2021-09 (4.21) we need a new AJDT
update site, because simply deploying to the 4.19 one would probably
lead to problems in the IDE.

Signed-off-by: Alexander Kriegisch <Alexander@Kriegisch.name>