On the build machine, code to test is in jars, not in 'bin' folders - so the aj.path for the LTW tests needs to have an entry for asm.jar in addition to the asm/bin it currently has.  Otherwise they fail with 'NoClassDefFoundError: org/aspectj/asm/IRelationship$Kind'